### ISSUE TITLE
Maps: Refactor and enhancements

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc-projects/AntAlmanac#112]
- [ ] Implement a carousel for multiple images
- [x] If multiple courses are at the same location, show number of overlapping courses and list all courses at the location
- [x] Use addedCourses instead of eventsInCalendar to create markers

**Comment by ChaseC99** [comment]
Clarification on the "Implement a carousel for multiple images"  
This is referring to how the Classrooms website has multiple images for each building. On the maps view, we could implement a card that cycles through each image. Not a huge priority issue though.
![image](https://user-images.githubusercontent.com/29494270/151779532-644b3fb8-3d64-4c65-8f75-40e010d151ef.png)

**Comment by kartik-bhagatwala** [comment]
Thanks for the input. I think I'll just submit the merge without the carousel. I was trying a couple third party libraries for the carousel but I ran into various bugs that I couldn't resolve when using those.

**Comment by ChaseC99** [comment]
What branch are you changes on? We'll want to make sure it doesn't conflict with #223
