### ISSUE TITLE
Integrate with Google Analytics

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc-projects/AntAlmanac#23]
We need to add analytics bindings to actions and button presses/page accesses so we can better understand what features are being used and focus on the most important features. 
We also need Google Analytics to get general statistics such as unique users etc.

We'll monitor the new site under the Google Analytics property `antalmanac-rewrite`

- [x] Add privacy policy notification/checkbox banner to site. A good place for this would be in the right pane at the bottom. Dismissing this should save a boolean to localStorage so it doesn't popup if that variable is set true in there.

**Track clicks on these actions below**
- [x] Left Pane - Kartik
  - [x] Click Screenshot button
  - [x] Click Custom Event button
  - [x] Click Clear button
  - [x] Click Undo button
- [x] Class search tab - William
  - [x] View/Click "Map" tab in right pane
  - [x] View/Click "Added Classes" tab in right pane
- [x] Top bar - Kartik
  - [x] Click "Settings"
  - [x] Click "Notifications"
  - [x] Toggle Dark Mode
- [x] Class search after completing search - William
  - [x] Click "Past Enrollment" button
  - [x] Click instructor name
  - [x] Click section code
- [x] Added classes tab - Monica
  - [x] Click copy schedule
  - [x] Click clear schedule
  - [x] Click on color to change course color
  - [x] Delete course

**Comment by devsdevsdevs** [comment]
Any thoughts on this as the privacy policy notice? Also tagging @ChaseC99 
![image](https://user-images.githubusercontent.com/30539874/106866928-e2fd5680-6681-11eb-94ce-218438353abd.png)

**Comment by ChaseC99** [comment]
> Any thoughts on this as the privacy policy notice? Also tagging @ChaseC99 
> 

LGTM 👍🏼
