### ISSUE TITLE
Removing classes in "Added Classes" page

### ISSUE THREAD

**Issue by braedons** [icssc-projects/AntAlmanac#46]
With multiple sections for the same course (ex: CS 112 Lec and Dis) added, clicking remove from either will remove it from the schedule calendar, but the right pane is unaffected. Removing both will then remove both sections.

With multiple courses added (ex: CS 112 Lec, CS 121 Lec, and CS 116 Lec), clicking remove always removes the bottom-most one from the right pane, but the schedule calendar is updated correctly.

At any point after deleting, if the right pane is incorrect, switching to a different tab, then back to "Added Classes", will make it correct again.

**Comment by devsdevsdevs** [comment]
@ChaseC99 Can you investigate? Tried to debug for an hr or so today...no dice

**Comment by ChaseC99** [comment]
Sure thing, I'll look into this tomorrow!
