### ISSUE TITLE
Unhandled TypeError in Class Search

### ISSUE THREAD

**Issue by braedons** [icssc-projects/AntAlmanac#56]
![image](https://user-images.githubusercontent.com/25188285/105065349-9e8f7b00-5a32-11eb-8c4b-18144a7a3864.png)

This occurs when doing a search without specifying any parameters beyond the (pre-filled) "term."

**Comment by devsdevsdevs** [comment]
Committed directly to develop since it was a fairly simple straightforward change: Added an error field in CourseRenderPane, set when network errors or non 200 code is returned from backend.
