### ISSUE TITLE
Navigate away confirmation

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc-projects/AntAlmanac#7]
The site up right now has this. When someone has made edits, we should ask them if they want to save changes before leaving the site.

**Comment by devsdevsdevs** [comment]
A good strategy would be to set a variable "edited" or something to true in the function `handleActions` (AppStore.js) when actions are triggered that modify `customEvents`, `addedCourses`, or `deletedCourses` fields. This variable would then be resetted on a load or save action.

**Comment by ChaseC99** [comment]
Should we also have a warning if they try to load another schedule before saving the current one that they have open?
